const path = require('path')
const CleanOutputPlugin = require('./clean-output-plugin')
const FileHeaderPlugin = require('./file-header-plugin')
const BuildInfoPlugin = require('./build-info-plugin')
const AnalyzeBundlePlugin = require('./analyze-bundle-plugin')

module.exports = (env, argv) => {
  const isProduction = argv.mode === 'production'
  
  return {
    mode: argv.mode || 'development',
    entry: './src/index.js',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: isProduction ? '[name].[contenthash].js' : '[name].js',
      clean: false
    },
    plugins: [
      // 清理输出目录插件
      new CleanOutputPlugin({
        outputPath: 'dist',
        verbose: isProduction
      }),

      // 文件头部注释插件（仅生产环境）
      ...(isProduction ? [
        new FileHeaderPlugin({
          header: `/**
 * Generated by Webpack Custom Plugins
 * Environment: ${argv.mode}
 * Build Date: ${new Date().toISOString()}
 * Author: Plugin Demo
 * License: MIT
 */
`,
          files: ['.js']
        })
      ] : []),

      // 构建信息插件
      new BuildInfoPlugin({
        filename: 'build-info.json',
        includeGitInfo: true,
        includePackageInfo: true,
        info: {
          environment: argv.mode,
          isProduction
        }
      }),

      // 包分析插件（仅生产环境）
      ...(isProduction ? [
        new AnalyzeBundlePlugin({
          outputDir: 'analysis',
          includeModules: true,
          includeAssets: true,
          threshold: 100 // 100 bytes 以上才分析
        })
      ] : [])
    ],
    
    // 开发环境配置
    devtool: isProduction ? 'source-map' : 'eval-cheap-module-source-map',
    
    // 优化配置（生产环境）
    ...(isProduction ? {
      optimization: {
        minimize: true,
        splitChunks: {
          chunks: 'all',
          cacheGroups: {
            vendor: {
              test: /[\\/]node_modules[\\/]/,
              name: 'vendors',
              chunks: 'all',
            }
          }
        }
      }
    } : {})
  }
}